apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: discovery-server
    spec:
      containers:
      - image: maheshd4077/springboot-microservices-k8s:discovery-server-V1.0
        name: springboot-microservices-k8s
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: discovery-server
  name: discovery-server
spec:
  ports:
  - name: "8761"
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: discovery-server
  type: ClusterIP
status:
  loadBalancer: {}
