apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-service
    spec:
      containers:
      - image: maheshd4077/springboot-microservices-k8s:account-service-V1.0
        name: springboot-microservices-k8s
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account-service
  name: account-service
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: account-service
  type: ClusterIP
status:
  loadBalancer: {}
