apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: getway-server
  name: getway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getway-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: getway-server
    spec:
      containers:
      - image: maheshd4077/springboot-microservices-k8s:gateway-server-V1.0
        name: springboot-microservices-k8s
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateway-server
  name: gateway-server
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateway-server
  type: NodePort
status:
  loadBalancer: {}
